name: Java CI for CloudSim VM Scheduling

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Compile with javac
      run: |
          mkdir -p out
          javac -cp "lib/*" -d out src/main/java/com/example/vmscheduling/*.java

    - name: Run main class
      run: |
          java -cp "lib/*:out" com.example.vmscheduling.VMSchedulingSimulator
  
